version: "3.9"
services:
  web:
    container_name: weatherpoint-frontend
    build:
      context: ./flowoftime
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: frontend.env
    volumes:
      - ./flowoftime:/app/
  backend:
    container_name: weatherpoint-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./backend/src/:/app/src/
    env_file:
      - backend.env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db:/db/data
